clone_depth: 1

environment:
  NODEJS_VERSION: "8"

install:
- ps: >-
    Install-Product node $env:NODEJS_VERSION

    choco install GoogleChrome | out-null

    choco install Firefox | out-null

    npm --version

    npm i --loglevel error

- cmd: >-
    npm install

build: off

test_script:
- cmd: >-
    npm test
